### ISSUE TITLE
1.6.60 throwing NoSuchMethodError exception

### ISSUE THREAD

**Issue by breser** [saucelabs/bamboo_sauce#28]
> java.lang.NoSuchMethodError: com.saucelabs.saucerest.SauceREST.getTunnelInformation(Ljava/lang/String;)Ljava/lang/String;
 	at > com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager.activeTunnelIdentifier(AbstractSauceTunnelManager.java:417)
	at com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager.openConnection(AbstractSauceTunnelManager.java:272)
	at com.saucelabs.bamboo.sod.action.BuildConfigurator.startTunnel(BuildConfigurator.java:158)
	at com.saucelabs.bamboo.sod.action.BuildConfigurator.call(BuildConfigurator.java:121)
	at com.atlassian.bamboo.build.pipeline.tasks.PrepareBuildTask.runPreBuildActions(PrepareBuildTask.java:134)
	at com.atlassian.bamboo.build.pipeline.tasks.PrepareBuildTask.call(PrepareBuildTask.java:102)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:188)
	at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:112)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:110)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
	at java.lang.Thread.run(Thread.java:745)

Unpacking the jar we find saucerest-1.0.20.jar which contains SauceRest and only has the following methods:

> Compiled from "SauceREST.java"
public class com.saucelabs.saucerest.SauceREST {
  protected java.lang.String username;
  protected java.lang.String accessKey;
  public static final java.lang.String RESTURL;
  public com.saucelabs.saucerest.SauceREST(java.lang.String, java.lang.String);
  public void jobPassed(java.lang.String);
  public void jobFailed(java.lang.String);
  public void downloadVideo(java.lang.String, java.lang.String);
  public void downloadLog(java.lang.String, java.lang.String);
  public java.lang.String retrieveResults(java.lang.String);
  public java.lang.String getJobInfo(java.lang.String);
  public java.lang.String retrieveResults(java.net.URL);
  protected void addAuthenticationProperty(java.net.HttpURLConnection);
  public void updateJobInfo(java.lang.String, java.util.Map<java.lang.String, java.lang.Object>);
  public void stopJob(java.lang.String);
  public java.net.HttpURLConnection openConnection(java.net.URL) throws java.io.IOException;
  public java.lang.String uploadFile(java.io.File) throws java.io.IOException;
  public java.lang.String uploadFile(java.io.File, java.lang.String) throws java.io.IOException;
  public java.lang.String uploadFile(java.io.File, java.lang.String, java.lang.Boolean) throws java.io.IOException;
  public java.lang.String getPublicJobLink(java.lang.String);
  protected java.lang.String encodeAuthentication();
  public void deleteTunnel(java.lang.String);
  public java.lang.String getTunnels();
  static {};
}

No getTunnelInformation method.

**Comment by breser** [comment]
Looking further into the rest API github repo I see this was added in 1.0.25.
https://github.com/saucelabs/saucerest-java/releases

**Comment by rossrowe** [comment]
Yep, thanks for letting me know, and apologies for the inconvenience.  I'm
just deploying a fix now, will let you know when a new version is ready

**Comment by rossrowe** [comment]
Hi again, I've just released version 1.6.61 which should include the
correct version of the Sauce REST API, can you try this version and let me
know how it goes?

**Comment by breser** [comment]
We've installed it this morning.  I'll know more tomorrow when tests that were running into this run overnight.

**Comment by breser** [comment]
No issues since we updated to 1.6.61.  Think it's safe to close this one.  Thanks for your quick response.
