### ISSUE TITLE
Can not install plugin on CentOS 6.8

### ISSUE THREAD

**Issue by emzeidan** [saucelabs/bamboo_sauce#43]
Hi team,

In my testing, I have not been able to install the plugin on CentOS 6.8 systems, running either OpenJDK or the Oracle JDK, and Bamboo 5.14.1, 5.15.0.1, and 5.15.3.

The error appears to be:
> java.lang.IncompatibleClassChangeError: Implementing class

Please see beginning of Stacktrace below:
> 2017-03-14 18:00:34,304 ERROR [UpmAsynchronousTaskManager:thread-2] [ScanningPluginLoader] Unable to deploy plugin 'com.saucelabs.bamboo.bamboo-sauceondemand-plugin' from 'Unit: /opt/atlassian/bamboo/bamboo-home/plugins/plugin.851885393880030240.bamboo-sauceondemand-plugin-1.6.76.jar (1489514432000)'.
> 2017-03-14 18:00:34,305 ERROR [UpmAsynchronousTaskManager:thread-2] [ScanningPluginLoader] Because of the following exception:
> java.lang.IncompatibleClassChangeError: Implementing class
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

Please let me know if I can provide any further details.

Thanks!

**Comment by halkeye** [comment]
sweet, another instance of this, maybe we can finally debug it.

Do you know what version of java you are using?

**Comment by emzeidan** [comment]
Hi @halkeye . 

I was using OpenJDK 1.8.0 (java-1.8.0-openjdk) and Oracle JDK (jdk-8u121-linux-x64.rpm) from the [Oracle download page](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).

Hope this helps!

**Comment by theCampbell** [comment]
Hiya @emzeidan y @halkeye ,
This could be a dependency for GLIBC v.2.14 , what version of GLIBC does the host Centos machine have?  If not 2.14 or greater than that would explain it, in which case a new host machine is needed or a compatible version of Sauce Connect would need to be run.  4.4.4 was altered to be compatible with 2.12 so upgrading to this version could be an option as we backed out this requirement to cover users still on older but still technically supported operating systems.

Cheers,
TheCampbell

**Comment by emzeidan** [comment]
Hi @theCampbell ,

Thanks for your help! My CentOS machine is using GLIBC v2.12. This could indeed be the issue.

Thanks!

**Comment by theCampbell** [comment]
Hiya @emzeidan ,
I could be mistaken though, @halkeye pointed out to me that the error is before SC even starts so I am prolly mistaken.  Ultimately @halkeye will know for sure.

Cheers,
TheCampbell

**Comment by pshowbs** [comment]
@halkeye @theCampbell : Hi this is the original submitter of the issue to Atlassian.  We are not use Sauce Connect and are simply trying to install the plugin on Bamboo server. If I understand correctly, we are out of luck trying to do so with our current OS? Are there any possible work arounds?

**Comment by halkeye** [comment]
I have no idea how to trigger this sorry.

from my googling it looks like its some sort of conflicting dependancy somewhere, but no easy way to track this down. Did atlassian say anything?

Can you email support@saucelabs.com and we'll get it bumped up in priority.

**Comment by pshowbs** [comment]
Atlassian was able to reproduce using Centos 6.8 as the server. We are on the latest 5.15.3 Bamboo version. I will email support and reference this.

**Comment by emzeidan** [comment]
@pshowbs : Hi, I am the Support Engineer that has been managing your Bamboo Support ticket. I think that the conflicting dependency may be correct. I apologize, I am not sure which dependencies may be conflicting.

**Comment by jdesulme** [comment]
Hi @halkeye we're also experiencing this issue but it's not just tied to Centos 6.5. We're seeing it across both our RHEL 6.2 environment and Ubuntu 14.04 environment.

```2017-06-20 18:08:16,798 ERROR [UpmAsynchronousTaskManager:thread-3] [ScanningPluginLoader] Unable to deploy plugin 'com.saucelabs.bamboo.bamboo-sauceondemand-plugin' from 'Unit: /var/vcap/store/atlassian-bamboo/plugins/plugin_2054569580536360615_bamboo-sauceondemand-p
lugin-1.6.78.jar (1497996495000)'.
2017-06-20 18:08:16,798 ERROR [UpmAsynchronousTaskManager:thread-3] [ScanningPluginLoader] Because of the following exception:
java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)```

**Comment by jdesulme** [comment]
We tried installing a variety of plugin versions from 1.6.71 to 1.6.78. They all failed to install properly error-ring out with same Implementing class error. An Atlassian article mentioned that it may have been built with Java 7 but I tried compiling it locally with Java 8 and it still failed using my local version. This is a major impact for our company because we have to completely disable the plugin to allow our bamboo instance to perform normally.

**Comment by ijeyanthan** [comment]
**Workaround**: List the contents of `<Bamboo install directory>/atlassian-bamboo/WEB-INF/lib` and check if you have more than 1 version of asm-*.jar. If found, the workaround, for now, is to delete/move the library `asm-commons-3.3.jar` from that folder and then restart Bamboo. Hope that helps.

_PS. The asm-commons.jar (which is part of this tool: http://asm.ow2.org/) is a dependency in Bamboo and it is not a good idea to remove it if you don't have a duplicate. Its removal would impact Maven builds, the REST API and possibly Bamboo server to remote agent communication._

**Comment by jdesulme** [comment]
@ijeyanthan Is this something that we should escalate to Atlassian than because they are providing the original install package? 

```
bamboo:/opt/atlassian-bamboo/atlassian-bamboo-standalone/atlassian-bamboo/WEB-INF/lib# ls asm-*
asm-3.3.jar  asm-5.0.3.jar  asm-commons-3.3.jar  asm-tree-3.3.jar
```
Also looking through my directory structure for Bamboo 5.15.7 I see `asm-3.3.jar` and `asm-5.0.3.jar` but don't see a double commons jar. Is that expected or is it different by installation?

**Comment by ijeyanthan** [comment]
@jdesulme You are right. It is just sufficient to delete `asm-commons-3.3.jar` and I believe Atlassian will fix it in the upcoming Bamboo releases.
